### ISSUE TITLE
healthcheck fails

### ISSUE THREAD

**Issue by djaydev** [spritsail/radarr#2]
Hi guys, great stuff. Can't remember when it started but recently the healthcheck is always showing "unhealthly" for me. I think the issue is the URL but this isn't really my specialty. 

current health check:
`CMD wget -qO /dev/null 'http://localhost:7878/api/system/status' \ ...`

my guess of a fix:
`CMD wget -qO /dev/null 'http://localhost:7878/api/v3/system/status' \ ...`

i got that from here https://radarr.video/docs/api/#/System/get-status

Thanks guys

**Comment by frebib** [comment]
You're right, I forgot to update the healthcheck URL when making the recent update:
https://github.com/spritsail/radarr/commit/3abfdc93156b3e937e0ed7df94a5fdc8d6f0ccec#diff-b54b39f1afced2465e1f3641db9d5bbf4f3a7fcf890996dfedd3c197bcb7f8c7R18
Would you be able to send a PR to fix that? 🙏🏻

**Comment by djaydev** [comment]
I'm just a dumb casual, how I send a PR?
